# 测试环境配置
app:
  environment: test

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/z_blogt?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: jiangxia
    password: "jiangxia123!@#"
  
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1

# 测试环境使用开发环境的日志配置
logging:
  level:
    root: INFO